Review of PR 301 to Discuss fixes of #164 #168 #169
nf-core/atacseq pull request #375
Opened 2024-07-12 16:24 UTC by lpantano

Effort to review previous PR that discussed important changes in the pipeline from @ktrns :

Fixed issue Genome annotation (gene names) missing in IGV session file  #168 – The genome is again written out so that the IGV session file can be opened and used. This bug came with atacseq v2.0
Fixed issue Peak calling parameters might not be ideal  #169 – Genome coverage tracks were generated & peaks were called based on fragments rather than reads, which is not correct for ATAC-seq analysis. This is fixed.
Implemented issue https://github.com/nf-core/atacseq/issues/164 (partly issue https://github.com/nf-core/atacseq/issues/91) – A new parameter ‘--shift_reads’ adjusts the coordinates of the reads using deeptools/alignmentsieve. At the moment this only works for paired-end data and throws an error if applied to single-end data.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/atacseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/atacseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-15 17:53 UTC, lpantano commented
@JoseEspinosa , do you think you can take a look, happy to do anything else to make it easier to review, thanks!

2024-08-17 14:20 UTC, JoseEspinosa commented
Hi, I am currently on holiday, I will try to take a look but I am not sure when I will be able to.
I was working on preparing a release for chipseq that is almost ready and my idea was to prepare it also for atacseq but did not have enough time. 
As there are many changes in the current dev branch and the change you are suggesting is quite a change for the pipeline I am tempted to instead of merging it to `dev` directly, first make a release of the pipeline with the current bug fixes and some other urgent fixes (version 2.2.0) and then a follow-up release with what you are proposing after doing some testing (version 2.3.0).
If you agree, then maybe I can create a branch to include your changes in the main repository `footprinting` maybe? and we will merge this PR to this new branch instead of `dev`, what do you think @lpantano ?

2024-08-20 14:16 UTC, lpantano commented
I am ok with that, my changes are not that big thought, I only applied the shift and it is turn off by default. I didn't end up changing anything else, because I saw that were major options like the change in the alignments. Take a look, and let me know, I am ok either way, as far as it is the path to get it for other people. This is something very standard done for ATACseq in many other pipelines so I think many people are interested. Thanks!

2024-09-19 15:22 UTC, apeltzer approved these changes
Some minor things, but overall ok. Would push the module to nf-core/modules and import from there if possible, looks quite good to me to do so ...

2024-09-19 15:22 UTC, apeltzer commented on CHANGELOG.md
> +- [[#164]](https://github.com/nf-core/atacseq/issues/164) and partly [[#91]](https://github.com/nf-core/atacseq/issues/91) with code from [[#301]](https://github.com/nf-core/atacseq/pull/301) to addr
```suggestion
- [[#164]](https://github.com/nf-core/atacseq/issues/164) and partly [[#91]](https://github.com/nf-core/atacseq/issues/91) with code from [[#301]](https://github.com/nf-core/atacseq/pull/301) to address shifting of reads as an option that is turned off by default.
```

2024-09-19 15:22 UTC, apeltzer commented on modules/local/deeptools_alignmentsieve.nf
Would rather push this to nf-core/modules - there is already other recipes for deeptools tools --> another one being added should be fairly easy to do :)

2024-09-19 15:22 UTC, apeltzer commented on modules/local/deeptools_alignmentsieve.nf
And it looks good :)

2024-09-19 17:35 UTC, lpantano commented on modules/local/deeptools_alignmentsieve.nf
yes, I will try to do that, it is true is already there so it should be even easier. thanks!

2024-09-25 20:17 UTC, JoseEspinosa requested changes
Some small suggestions, mostly formatting issues. I realised that for `chromap` we are applying the shift always, I will open an issue and by default will run chromap without shifting if the parameter `shift_reads` is not set.

2024-09-25 20:17 UTC, JoseEspinosa commented on workflows/atacseq.nf
> +include { BAM_SHIFT_READS as MERGED_REPLICATE_BAM_SHIFT_READS } from '../subworkflows/local/bam_shift_reads'
```suggestion
include { BAM_SHIFT_READS as MERGED_LIBRARY_BAM_SHIFT_READS                   } from '../subworkflows/local/bam_shift_reads'
include { BAM_SHIFT_READS as MERGED_REPLICATE_BAM_SHIFT_READS                 } from '../subworkflows/local/bam_shift_reads'
```

2024-09-25 20:17 UTC, JoseEspinosa commented on nextflow_schema.json
> +                    "help_text": "Shift aligned reads as commonly done for ATACseq, +4bp for reads on the + strand, -5 bp for reads on the - strand. This can only be applied if all samples are paired
Usually, this is done for footprinting, should we add it to the `help_text`?
```suggestion
                    "help_text": "Shift aligned reads as commonly done for ATACseq footprinting analysis, +4 bp for reads on the + strand, -5 bp for reads on the - strand. This can only be applied if all samples are paired-end.",
```

2024-09-25 20:17 UTC, JoseEspinosa commented on modules/local/deeptools_alignmentsieve.nf
> +process DEEPTOOLS_ALIGNMENTSIEVE {
I agree @apeltzer and opened an [issue](https://github.com/nf-core/modules/issues/6690) in the modules repo to create the module there, by the moment we can leave it local in `dev`

2024-09-25 20:17 UTC, JoseEspinosa commented on subworkflows/local/bam_shift_reads.nf
> +include { DEEPTOOLS_ALIGNMENTSIEVE } from '../../modules/local/deeptools_alignmentsieve'
```suggestion
include { SAMTOOLS_SORT            } from '../../modules/nf-core/samtools/sort/main'
include { SAMTOOLS_INDEX           } from '../../modules/nf-core/samtools/index/main'
include { SAMTOOLS_FLAGSTAT        } from '../../modules/nf-core/samtools/flagstat/main'
include { DEEPTOOLS_ALIGNMENTSIEVE } from '../../modules/local/deeptools_alignmentsieve'
```

2024-09-25 20:17 UTC, JoseEspinosa commented on nextflow_schema.json
> +                    "description": "Shift aligned reads (+4bp and -5bp)."
```suggestion
                    "description": "Shift aligned reads (+4 bp and -5 bp)."
```

2024-09-25 20:17 UTC, JoseEspinosa commented on workflows/atacseq.nf
> +    ch_merged_library_filter_csi = MERGED_LIBRARY_FILTER_BAM.out.csi
```suggestion
    ch_merged_library_filter_bam      = MERGED_LIBRARY_FILTER_BAM.out.bam
    ch_merged_library_filter_bai      = MERGED_LIBRARY_FILTER_BAM.out.bai
    ch_merged_library_filter_flagstat = MERGED_LIBRARY_FILTER_BAM.out.flagstat
    ch_merged_library_filter_csi      = MERGED_LIBRARY_FILTER_BAM.out.csi
```

2024-09-25 20:17 UTC, JoseEspinosa commented on workflows/atacseq.nf
> +        ch_merged_library_filter_csi = MERGED_LIBRARY_BAM_SHIFT_READS.out.csi
```suggestion
        ch_merged_library_filter_bam      = MERGED_LIBRARY_BAM_SHIFT_READS.out.bam
        ch_merged_library_filter_bai      = MERGED_LIBRARY_BAM_SHIFT_READS.out.bai
        ch_merged_library_filter_flagstat = MERGED_LIBRARY_BAM_SHIFT_READS.out.flagstat
        ch_merged_library_filter_csi      = MERGED_LIBRARY_BAM_SHIFT_READS.out.csi
```

2024-09-25 20:17 UTC, JoseEspinosa commented on workflows/atacseq.nf
> +        // ch_chrom_sizes
```suggestion
```

2024-09-25 20:17 UTC, JoseEspinosa commented on workflows/atacseq.nf
> +        ch_merged_replicate_markduplicate_csi = MERGED_REPLICATE_MARKDUPLICATES_PICARD.out.csi
```suggestion
        ch_merged_replicate_markduplicate_bam      = MERGED_REPLICATE_MARKDUPLICATES_PICARD.out.bam
        ch_merged_replicate_markduplicate_bai      = MERGED_REPLICATE_MARKDUPLICATES_PICARD.out.bai
        ch_merged_replicate_markduplicate_flagstat = MERGED_REPLICATE_MARKDUPLICATES_PICARD.out.flagstat
        ch_merged_replicate_markduplicate_csi      = MERGED_REPLICATE_MARKDUPLICATES_PICARD.out.csi
```

2024-09-25 20:17 UTC, JoseEspinosa commented on workflows/atacseq.nf
> +            ch_merged_replicate_markduplicate_csi = MERGED_REPLICATE_BAM_SHIFT_READS.out.csi
```suggestion
            ch_merged_replicate_markduplicate_bam      = MERGED_REPLICATE_BAM_SHIFT_READS.out.bam
            ch_merged_replicate_markduplicate_bai      = MERGED_REPLICATE_BAM_SHIFT_READS.out.bai
            ch_merged_replicate_markduplicate_flagstat = MERGED_REPLICATE_BAM_SHIFT_READS.out.flagstat
            ch_merged_replicate_markduplicate_csi      = MERGED_REPLICATE_BAM_SHIFT_READS.out.csi
```

2024-09-26 09:13 UTC, JoseEspinosa approved these changes
Thanks! Awesome job 🚀

2024-09-26 09:14 UTC, merged